apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3

  selector:
    matchLabels:
      app: my-nginx-app-index

  template:
    metadata:
      name: my-nginx-app-index
      labels:
        app:  my-nginx-app-index
    spec:
      containers:
        - name: pro-image
          image: amrayyad/pro
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80